### ISSUE TITLE
Validation data on SRA

### ISSUE THREAD

**Issue by probalica19** [getzlab/deTiN#29]
Hi, 

I would like to do some benchmarking with the validation data you have generated and shared through SRA [PRJNA422575](https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA422575).

Could you please provide more information what exactly do the **Library Names** mean?

- There are two prefixes - **HCC** and **TiN** - what do they correspond to?
- In samples whose Library names start with **HCC** (e.g. [HCC_70_30](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR6438473)) - is 70 for the tumor and 30 for the normal or vice versa?
- n samples whose Library names start with **TiN** (e.g. [TiN_12_5](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR6438464)) - what do numbers 12 and 5 correspond to?
- For TiN samples, what are the calculated/expected purities?

Thank you very much in advance and thank you for this amazing data!

probalica

**Comment by amarotaylor** [comment]
Hi probalica,

HCC refers to the cell line. TiN refers to tumor in normal. The reason for the different names is that some of these (HCC-prefixed) were generated as part of a benchmarking study done previously to the development of DeTiN and some of them (TiN-prefixed) were created specifically for DeTiN benchmarking. I believe 70_30 corresponds to 70% Tumor and 30% Normal though I am no longer at the broad and can't access this data / my old compute env to check. TiN libraries are more clearly named TiN_12_5 corresponds to a sample that was mixed to be 12.5% tumor 87.5% Normal. 

For all samples purity is expected to be 100% in that the specific mixture directly corresponds the DNA. However as was noted in the manuscript -- this cell line is multi-clonal such that the "purity" for a specific subclone (as is the case in natural samples) wont be exactly matched and some clones are shared between tumor and normal lineages (making some events difficult to completely characterize). Hope that helps.

Best
Amaro

**Comment by probalica19** [comment]
Dear Amaro, 

Thank you very much for your answer, this was very helpful.

I still have one more question - in the paper it is mentioned that there were two different simulated datasets *in sillico* and *in vitro*. As I understood, *in sillico* corresponds to downsampling and mixing tumor and normal BAM files from HCC1143, while *in vitro* corresponds to mixing cell lines in laboratory conditions and sequencing of such mixtures.

Could you please explain to which of these two experiments does data in PRJNA422575 correspond to? Is it the same for samples named 'TiN' and 'HCC', mentioned in the previous comments?

Thank you very much in advance!

Kind regards, 
probalica
