### ISSUE TITLE
error while generating ExAC file

### ISSUE THREAD

**Issue by MariusGheorghe** [getzlab/deTiN#30]
Hi,

I am trying to get your tool to actually work (which has proven not to be an easy task) and while trying to find instructions on how to generate the ExAC file (besides your only one line in the Wiki), I get the following error:

```
>>> deTiN.deTiN_utilities.build_exac_pickle("./ExAC.r0.3.1.sites.vep.vcf.gz")
Filtering ExAC sites from candidate mutations
processed 0 ExAC sites
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "deTiN-2.0.1/deTiN/deTiN_utilities.py", line 655, in build_exac_pickle
    spl = line.strip("\n").split("\t")
TypeError: a bytes-like object is required, not 'str'
```
The file was downloaded from ftp://ftp.broadinstitute.org/pub/ExAC_release/current

Any idea why this is? Did you maintain forward compatibility with the ExAC files? Do you still maintain this tool?
Thank you in advance

Marius

**Comment by amarotaylor** [comment]
closing this since were discussing in the other thread. https://github.com/getzlab/deTiN/issues/14#issuecomment-713550207
