### ISSUE TITLE
Easy Question: Is "alt_allele_in_normal" from Mutect1 is similar to "normal artifact" in Mutect2(GATK4)

### ISSUE THREAD

**Issue by Admera2020** [getzlab/deTiN#35]
Hello,

I have a very quick and perhaps a basic question. I am trying to use the latest version of Mutect2  via GATK4. The only constrain I have is that the latest version of the Mutect2 does not have FILTER "alt_allele_in_normal" in the VCF. Instead, I do see "normal artifact" in the newer version.

Do you have any experience running DeTiN with a variant noted as  "normal artifact" as the failure reason?

Best

**Comment by amarotaylor** [comment]
Hi Admera

I don't have any experience with normal artifact. Reading the docs quickly it seems like its based on the same LOD score as tumor LOD. I would treat that flag as a variant we want to consider in DeTiN's model. Seems like its almost equivalent to alt_allele_in_normal.

**Comment by Admera2020** [comment]
Thank you very much for your quick response.
